### ISSUE TITLE
请问DeepSpeed与Multi-gpu是绑定的吗？使用DeepSpeed提升效果有多大？

### ISSUE THREAD

**Issue by nameless0704** [lich99/ChatGLM-finetune-LoRA#10]
lora_finetune_with_stanford_alpaca.ipynb如何直接改成Multi-GPU训练？因为DeepSpeed不支持Windows系统。以及DeepSpeed对finetune的提升效果有多大？

**Comment by lich99** [comment]
可以不使用deepspeed，在trainer.py里去掉就行。

**Comment by nameless0704** [comment]
> 可以不使用deepspeed，在trainer.py里去掉就行。主要在batch比较大的时候影响稍大，其他区别不大。

万分感谢！！
