### ISSUE TITLE
数据集和微调模型的一些问题

### ISSUE THREAD

**Issue by Im-ShiShaoK** [lich99/ChatGLM-finetune-LoRA#2]
请问目前支持中文数据集吗？还有就是试着加载了库里的chatglm-6b_alpaca_5.pt这个模型，但是好像并没有起什么作用
![1](https://user-images.githubusercontent.com/98707554/226112666-a87e8b71-e75a-4046-99e5-f20cb2be5539.png)
![2](https://user-images.githubusercontent.com/98707554/226112667-76090126-37b6-4988-9e9a-e63f901130c8.png)

**Comment by lich99** [comment]
alpaca dataset这个是example, 估计ChatGLM原本的训练数据已经包括类似数据. 所以实际使用的时候还是要构造自己的数据集来实验.
