### ISSUE TITLE
ValueError: 150004 is not in list是什么回事？

### ISSUE THREAD

**Issue by z1968357787** [lich99/ChatGLM-finetune-LoRA#28]
![image](https://user-images.githubusercontent.com/103940793/230755618-3b885234-89e5-4722-85de-36e41bfd037c.png)

**Comment by manakanemu** [comment]
chatglm 删除了前20000个不用的token。把150004改成130004就行了

**Comment by z1968357787** [comment]
好的非常感谢


变质的水果糖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lich99/ChatGLM-finetune-LoRA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 晚上11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lich99/ChatGLM-finetune-LoRA] ValueError: 150004 is not in list是什么回事？ (Issue #28)





 
chatglm 删除了前20000个不用的token。把150004改成130004就行了

**Comment by fxb392** [comment]
ValueError: 130004 is not in list这又是为什么呢xdm
