### ISSUE TITLE
训练超显存

### ISSUE THREAD

**Issue by GaoPengGit** [lich99/ChatGLM-finetune-LoRA#3]
请问这个模型训练显存至少要多少？我这里是V100 32GB

**Comment by lich99** [comment]
可以进行一下长度限制, 我这边实验bf16/fp16, 限制在1024的最大长度, 24G可以存下

**Comment by xtc1989** [comment]
> 可以进行一下长度限制, 我这边实验bf16/fp16, 限制在1024的最大长度, 24G可以存下

是数据集处理时直接截到1024长度吗？

**Comment by GaoPengGit** [comment]
能问一下具体的操作方式吗？我这边设置max length=1024，GPU显存还是到了29GB
