### ISSUE TITLE
位置编码

### ISSUE THREAD

**Issue by fxb392** [lich99/ChatGLM-finetune-LoRA#45]
项目里用的二维位置编码吗？
但是chatGLM不是用的旋转位置编码吗？
@lich99 
> position_ids.append(torch.stack([torch.arange(0, _max_length, device=device), 
                                         torch.concat([torch.zeros(context_length - 1, device=device), 
                                                       torch.arange(0, _max_length - context_length + 1, device=device)])]).long())

**Comment by lich99** [comment]
chatGLM-6b 默认使用的还是二维位置编码

https://huggingface.co/THUDM/chatglm-6b/blob/main/config.json
`"position_encoding_2d": true` 

chatGLM2 使用的是旋转位置编码

**Comment by fxb392** [comment]
但是这个self attention里面有RoteryEmbedding
> ChatGLMForConditionalGeneration(
>   (transformer): ChatGLMModel(
>     (word_embeddings): Embedding(130528, 4096)
>     (layers): ModuleList(
>       (0-27): 28 x GLMBlock(
>         (input_layernorm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
>         (attention): SelfAttention(
>           (rotary_emb): RotaryEmbedding()
>           (query_key_value): Linear(in_features=4096, out_features=12288, bias=True)
>           (dense): Linear(in_features=4096, out_features=4096, bias=True)
>         )
>         (post_attention_layernorm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
>         (mlp): GLU(
>           (dense_h_to_4h): Linear(in_features=4096, out_features=16384, bias=True)
>           (dense_4h_to_h): Linear(in_features=16384, out_features=4096, bias=True)
>         )
>       )
>     )
>     (final_layernorm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
>   )
>   (lm_head): Linear(in_features=4096, out_features=130528, bias=False)
> )
>

**Comment by lich99** [comment]
是的, 但是没有使用
