### ISSUE TITLE
NameError: name 'train_dataloader' is not defined

### ISSUE THREAD

**Issue by wccccp** [lich99/ChatGLM-finetune-LoRA#5]
lr_scheduler = get_linear_schedule_with_warmup(
    optimizer=optimizer,
    num_warmup_steps=int(len(train_dataloader) / accumulate_step),
    num_training_steps=(int(len(train_dataloader) / accumulate_step) * NUM_EPOCHS),
)

**Comment by lich99** [comment]
look `LoRA_finetune_with_stanford_alpaca.ipynb` instead, if you need dataloader. please remember: This dataset is for demonstration purposes only.
