### ISSUE TITLE
About multi-GPU

### ISSUE THREAD

**Issue by zhongtao93** [lich99/ChatGLM-finetune-LoRA#9]
Is there any command and ymal example about `using accelerate to launch train.py`?

**Comment by lich99** [comment]
run `accelerate config` to generate the yaml file

**Comment by zhongtao93** [comment]
Encountered the following problem:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/15263824/227828581-a6b88f3f-d588-4be5-aa98-97a4ba2e7a0a.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/15263824/227828642-14efd217-8643-4f0a-a37c-5fd466b4ed98.png">

**Comment by lich99** [comment]
This message means OOM

**Comment by lich99** [comment]
You can manually filter out some of the excessively long data. For example, to drop the lines that are over 768 words.
